### ISSUE TITLE
El nombre del hermano de Natsume

### ISSUE THREAD

**Issue by Dieg0621** [REY3DS/YKW4_ES#2]
Cuando estas hablando con Natsume al final del cap 1 llama a su hermano keisuke y luego más adelante lo llama keisuke, el cual es el nombre correcto

**Comment by hbc-dev** [comment]
Se dió soporte al error en las nuevas versiones del mod.
Puedes descargar la nueva versión del mod desde este enlace => https://github.com/REY3DS/YKW4_ES/releases/latest
