### ISSUE TITLE
Acerca del proyecto

### ISSUE THREAD

**Issue by luishidalgoa** [REY3DS/YKW4_ES#5]
Hola, soy Luis y soy desarrollador de software. Soy un fan de yo-kay watch y en general de muchos de los juegos de Level-5 . Me encanta el proyecto que estais desarrollando. 

Perdonad que use Issues para esta pregunta pero si no es informacion reservada me gustaria conocer que tipo de tecnologias y lenguajes usais para desarrollar este tipo de proyecto, siempre he tenido interes en conocer las tripas de este tipo de proyectos fandom para mi desarrollo profesional.

Saludos y animo para seguir con esta bonita labor 😊

**Comment by REY3DS** [comment]
Muy buenas Luis, la verdad que si te soy sincero las herramientas que usamos no son demasiado difíciles de entender, cualquier persona con un poco de cabeza y paciencia podría usarlas, normalmente usamos 2 programas (kuriimu y kuriimu2) además de algunos scripts para arreglar errores que pueden llegar a dar estos programas.

Un saludo.

**Comment by luishidalgoa** [comment]
Thansk :)
