### ISSUE TITLE
Error al iniciar el juego

### ISSUE THREAD

**Issue by PolitoFdez24** [REY3DS/YKW4_ES#7]
Al iniciar el juego, en el prompt, aparece una secuencia de errores y, posteriormente, se cierra el programa. Adjunto una serie de imágenes que pueden ser de utilidad para saber donde está el problema.
![Captura de pantalla 2024-02-27 172129](https://github.com/REY3DS/YKW4_ES/assets/161510001/95b6b28c-2773-4a69-bd4f-b6b4721f4f62)
![Captura de pantalla 2024-02-27 193950](https://github.com/REY3DS/YKW4_ES/assets/161510001/32f7d008-623d-4e0f-a524-33704838574c)
![Captura de pantalla 2024-02-27 194018](https://github.com/REY3DS/YKW4_ES/assets/161510001/781ae64e-f559-4706-aab3-5bd7e85b81de)

**Comment by REY3DS** [comment]
no tienes lo necesario para ejecutar la traducción del juego.

**Comment by PolitoFdez24** [comment]
Y que más hace falta?

**Comment by Nigo10** [comment]
> Y que más hace falta?

Necesitas la actualización 2.2.0 (no la 2.0.0) y por lo que veo aparte te faltan las Keys y el Firmware
