### ISSUE TITLE
Crashea al entrar al primer combate del juego en ryujinx

### ISSUE THREAD

**Issue by Queso924** [REY3DS/YKW4_ES#8]
craseha el emulador al entrar en el primer combate del juego

**Comment by REY3DS** [comment]
tienes la actualizacion 2.2.0 y el dlc++ ?

**Comment by Queso924** [comment]
Si, se supone que tengo la actu 2.2.0 y los todos los dlcs

**Comment by REY3DS** [comment]
no es necesario todos los dlc, el importante es el dlc ++,  si me mandas una captura de tu carpeta de dlcs te puedo decir si lo tienes o no

**Comment by Queso924** [comment]
![Captura de pantalla 2024-03-05 121241](https://github.com/REY3DS/YKW4_ES/assets/101360632/011b0034-0857-4164-8c6e-76cb00ea924a)
