### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by Tonyxx00** [REY3DS/YKW4_ES#9]
En las habilidades de reloj de Natsume, las mejoras de Cuerpo, la de buenas espiritaciones, dice "positibas", cuando seria positivas.
La visión general de todas las mejoras de reloj, salen demasiado hacia la derecha, se corta parte de las letras.

**Comment by Nigo10** [comment]
¡Gracias por el comentario! ¡Para la siguiente versión ya estará corregido!
